import Header from '@/components/header'
import { StyledComponentsRegistry } from '@/components/styled-components-registry'
import { ReduxProvider } from '@/providers/redux-provider'
import { ThemeProvider } from '@/providers/theme-provider'
import { GlobalStyles } from '@/styles/global-style'
import type { Metadata } from 'next'
import { Bangers, Inter } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next'

const inter = Inter({})
const bangers = Bangers({ weight: '400' })

export const metadata: Metadata = {
  title: 'Marvel comics store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={inter.className + bangers.className}
      suppressHydrationWarning
    >
      <body>
        <NuqsAdapter>
          <ThemeProvider>
            <ReduxProvider>
              <GlobalStyles />
              <StyledComponentsRegistry>
                <Header />
                {children}
              </StyledComponentsRegistry>
            </ReduxProvider>
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
