import { StyledComponentsRegistry } from '@/components/styled-components-registry'
import { GlobalStyles } from '@/styles/global-style'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Marvel comics store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
